language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6

before_install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build && cd build
- cmake ..
- make
- cd ..
- rm -rf build
- mkdir build && cd build
- cmake -DPLATFORM:STRING=Android_x86 ..
- make
